// Available sign animations, this is hardcoded for now
// TODO: will have to inspect folder, and do this automatically
export const availableSigns2 = [
  { name: "HALLO", file: "signs/HALLO-C_250226_1.glb", start:60, end: 100 },
  { name: "SCHOOL", file: "signs/SCHOOL-D_250226_1.glb", start: 40, end: 110 },
  { name: "HAARLEM", file: "signs/HAARLEM_250226_1.glb", start: 15, end: 90 },
  { name: "KRIJGEN-A", file: "signs/KRIJGEN-A_250228_5.glb", start: 60, end: 110 },
  { name: "LELYSTAD", file: "signs/LELYSTAD_250314_1.glb", start:55, end: 130 },
  { name: "LES", file: "signs/LES_250228_2.glb", start: 85, end: 150 },
  { name: "PROBEREN-E", file: "signs/PROBEREN-E_250226_2.glb", start: 50, end: 117 },
  { name: "SCHULDGEVEN", file: "signs/SCHULDGEVEN_250226_1.glb", start: 50, end: 90 },
  { name: "VRAGEN-A", file: "signs/VRAGEN-A_250226_1.glb", start: 65, end: 100 },
  { name: "WACHTEN-B", file: "signs/WACHTEN-B_250226_1.glb", start: 30, end: 103 },
  {name: "lelystad", file: "signs/LELYSTAD_250314_1_GlassesGuyRecord_C_1.glb", start:55, end: 130 },
  {name: "2", file: "signs/mabel/2.glb", start: 0, end: 200 },
  {name: "3", file: "signs/mabel/3.glb", start: 0, end: 200 },
  {name: "4", file: "signs/mabel/4.glb", start: 0, end: 200 },
  {name: "Zin_250528_75.glb", file: "signs/mabel/Zin_250528_75.glb", start: 0, end: 500 },
  {name: "Trein", file: "signs/mabel/Trein_250528_59.glb", start: 0, end: 500 },
];

export const availableSigns = [
  // Root signs
  {name: "HALLO", file: "signs/HALLO-C_250226_1.glb", start:60, end: 100, folder: "root" },
  {name: "SCHOOL", file: "signs/SCHOOL-D_250226_1.glb", start: 40, end: 110, folder: "root" },
  {name: "HAARLEM", file: "signs/HAARLEM_250226_1.glb", start: 15, end: 90, folder: "root" },
  {name: "KRIJGEN-A", file: "signs/KRIJGEN-A_250228_5.glb", start: 60, end: 110, folder: "root" },
  {name: "LELYSTAD", file: "signs/LELYSTAD_250314_1.glb", start:55, end: 130, folder: "root" },
  {name: "LES", file: "signs/LES_250228_2.glb", start: 85, end: 150, folder: "root" },
  {name: "PROBEREN-E", file: "signs/PROBEREN-E_250226_2.glb", start: 50, end: 117, folder: "root" },
  {name: "SCHULDGEVEN", file: "signs/SCHULDGEVEN_250226_1.glb", start: 50, end: 90, folder: "root" },
  {name: "VRAGEN-A", file: "signs/VRAGEN-A_250226_1.glb", start: 65, end: 100, folder: "root" },
  {name: "WACHTEN-B", file: "signs/WACHTEN-B_250226_1.glb", start: 30, end: 103, folder: "root" },
  {name: "KIJKEN-NAAR-ELKAAR", file: "signs/KIJKEN-NAAR-ELKAAR_250228_1.glb", start: 0, end: null, folder: "root" },
  {name: "wachten-modified", file: "signs/wachten-modified.glb", start: 0, end: null, folder: "root" },

  // Trein folder
  {name: "1", file: "signs/trein/1.glb", start: 90, end: 140, folder: "trein" },
  {name: "2", file: "signs/trein/2.glb", start: 95, end: 150, folder: "trein" },
  {name: "3", file: "signs/trein/3.glb", start: 90, end: 150, folder: "trein" },
  {name: "4", file: "signs/trein/4.glb", start: 90, end: 150, folder: "trein" },
  {name: "5", file: "signs/trein/5.glb", start: 90, end: 150, folder: "trein" },
  {name: "6", file: "signs/trein/6.glb", start: 90, end: 150, folder: "trein" },
  {name: "7", file: "signs/trein/7.glb", start: 90, end: 150, folder: "trein" },
  {name: "8", file: "signs/trein/8.glb", start: 90, end: 150, folder: "trein" },
  {name: "9", file: "signs/trein/9.glb", start: 90, end: 150, folder: "trein" },
  {name: "10", file: "signs/trein/10.glb", start: 90, end: 150, folder: "trein" },
  {name: "11", file: "signs/trein/11.glb", start: 100, end: 150, folder: "trein" },
  {name: "12", file: "signs/trein/12.glb", start: 110, end: 150, folder: "trein" },
  {name: "13", file: "signs/trein/13.glb", start: 95, end: 150, folder: "trein" },
  {name: "14", file: "signs/trein/14.glb", start: 90, end: 150, folder: "trein" },
  {name: "15", file: "signs/trein/15.glb", start: 90, end: 150, folder: "trein" },
  {name: "5 OVER", file: "signs/trein/5_Over.glb", start: 80, end: 170, folder: "trein" },
  {name: "5 VOOR", file: "signs/trein/5_Voor.glb", start: 80, end: 180, folder: "trein" },
  {name: "10 OVER", file: "signs/trein/10_Over.glb", start: 60, end: 160, folder: "trein" },
  {name: "10 VOOR", file: "signs/trein/10_Voor.glb", start: 60, end: 160, folder: "trein" },
  {name: "A", file: "signs/trein/A.glb", start: 80, end: 110, folder: "trein" },
  {name: "B", file: "signs/trein/B.glb", start: 90, end: 120, folder: "trein" },
  {name: "AMSTERDAM", file: "signs/trein/Amsterdam.glb", start: 90, end: 180, folder: "trein" },
  {name: "DEN HAAG", file: "signs/trein/Den_Haag.glb", start: 90, end: 160, folder: "trein" },
  {name: "DIEMEN", file: "signs/trein/Diemen.glb", start: 90, end: 160, folder: "trein" },
  {name: "GRONINGEN", file: "signs/trein/Groningen.glb", start: 95, end: 190, folder: "trein" },
  {name: "HAARLEM", file: "signs/trein/Haarlem.glb", start: 110, end: 170, folder: "trein" },
  {name: "TREIN", file: "signs/trein/Trein.glb", start: 90, end: 160, folder: "trein" },
  {name: "INTERCITY", file: "signs/trein/Intercity.glb", start: 85, end: 135, folder: "trein" },
  {name: "SPRINTER", file: "signs/trein/Sprinter.glb", start: 90, end: 155, folder: "trein" },
  {name: "PERRON", file: "signs/trein/Perron.glb", start: 85, end: 155, folder: "trein" },
  {name: "SPOOR", file: "signs/trein/Spoor.glb", start: 85, end: 160, folder: "trein" },
  {name: "VERTREKT", file: "signs/trein/Vertrekt.glb", start: 100, end: 175, folder: "trein" },
  {name: "VERTREKT OVER", file: "signs/trein/Vertrekt_Over.glb", start: 90, end: 200, folder: "trein" },
  {name: "VERTREKT OM", file: "signs/trein/Vertrekt_Om.glb", start: 90, end: 200, folder: "trein" },
  {name: "VERTREKT VAN", file: "signs/trein/Vertrekt_Van.glb", start: 90, end: 200, folder: "trein" },
  {name: "VERTRAAGD", file: "signs/trein/Vertraagd.glb", start: 70, end: 165, folder: "trein" },
  {name: "VAN", file: "signs/trein/Van.glb", start: 95, end: 135, folder: "trein"},
  {name: "NAAR", file: "signs/trein/Naar.glb", start: 90, end: 150, folder: "trein" },
  {name: "OM", file: "signs/trein/Om.glb", start: 40, end: 105, folder: "trein" },
  {name: "OVER", file: "signs/trein/Over.glb", start: 90, end: 200, folder: "trein" },
  {name: "OVER2", file: "signs/trein/Over2.glb", start: 90, end: 200, folder: "trein" },
  {name: "VOOR", file: "signs/trein/Voor.glb", start: 90, end: 150, folder: "trein" },
  {name: "HALF", file: "signs/trein/Half.glb", start: 90, end: 160, folder: "trein" },
  {name: "KWART OVER", file: "signs/trein/Kwart_Over.glb", start: 90, end: 190, folder: "trein" },
  {name: "KWART VOOR", file: "signs/trein/Kwart_Voor.glb", start: 90, end: 190, folder: "trein" },
  {name: "MINUTEN", file: "signs/trein/Minuten.glb", start: 85, end: 130, folder: "trein" },
  {name: "MINUUT", file: "signs/trein/Minuut.glb", start: 90, end: 135, folder: "trein" },
  {name: "BESTE REIZIGERS", file: "signs/trein/Beste_Reizigers.glb", start: 85, end: 250, folder: "trein" },
  {name: "getallen", file: "signs/trein/getallen_250528_42.glb", start: 0, end: null, folder: "trein" },
  {name: "ZIN 1", file: "signs/trein/Zin_1.glb", start: 0, end: null, folder: "trein"},
  {name: "ZIN 2", file: "signs/trein/Zin_2.glb", start: 0, end: null, folder: "trein"},
  {name: "ZIN 3", file: "signs/trein/Zin_3.glb", start: 0, end: null, folder: "trein"},
  {name: "ZIN 4", file: "signs/trein/Zin_4.glb", start: 0, end: null, folder: "trein"},
  {name: "ZIN 5", file: "signs/trein/Zin_5.glb", start: 0, end: null, folder: "trein"},
  {name: "ZIN 6", file: "signs/trein/Zin_6.glb", start: 0, end: null, folder: "trein"},
  {name: "ZIN 7", file: "signs/trein/Zin_7.glb", start: 0, end: null, folder: "trein"},
  {name: "ZIN 8", file: "signs/trein/Zin_8.glb", start: 0, end: null, folder: "trein"},
  {name: "ZIN 9", file: "signs/trein/Zin_9.glb", start: 0, end: null, folder: "trein"},
  {name: "ZIN 10", file: "signs/trein/Zin_10.glb", start: 0, end: null, folder: "trein"},
  {name: "Zin_250528_75", file: "signs/trein/Zin_250528_75.glb", start: 0, end: null, folder: "trein"},

  // HH Gebaar folder
  {name: "1 (HH)", file: "signs/hh/gebaar/1_250507_12.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "2 (HH)", file: "signs/hh/gebaar/2_250507_13.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "3 (HH)", file: "signs/hh/gebaar/3_250507_14.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "5 (HH)", file: "signs/hh/gebaar/5_250507_15.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "12 (HH)", file: "signs/hh/gebaar/12_250507_37.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "18 (HH)", file: "signs/hh/gebaar/18_250507_42.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "70 (HH)", file: "signs/hh/gebaar/70_250507_43.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "alcohol", file: "signs/hh/gebaar/alcohol_250507_46.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "alleen", file: "signs/hh/gebaar/alleen_250507_30.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "arts", file: "signs/hh/gebaar/arts_250507_32.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "auto", file: "signs/hh/gebaar/auto_250507_52.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "auto rijden", file: "signs/hh/gebaar/auto_rijden_250507_51.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "beinvloeden", file: "signs/hh/gebaar/beinvloeden_250507_48.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "bewaar", file: "signs/hh/gebaar/bewaar_250507_17.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "buiten bereik", file: "signs/hh/gebaar/buiten_bereik_250507_22.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "bus", file: "signs/hh/gebaar/bus_250507_55.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "dosis", file: "signs/hh/gebaar/dosis_250507_16.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "drink", file: "signs/hh/gebaar/drink_250507_51.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "droog", file: "signs/hh/gebaar/droog_250507_19.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "fiets", file: "signs/hh/gebaar/fiets_250507_53.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "fietsen", file: "signs/hh/gebaar/fietsen_250507_53.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "ga", file: "signs/hh/gebaar/ga_250507_61.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "gebruik", file: "signs/hh/gebaar/gebruik_250507_27.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "keer", file: "signs/hh/gebaar/keer_250507_10.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "kinderen", file: "signs/hh/gebaar/kinderen_250507_34.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "kinderen (alt)", file: "signs/hh/gebaar/kinderen_250507_35.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "koel", file: "signs/hh/gebaar/koel_250507_18.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "laatste dosis", file: "signs/hh/gebaar/laatste_dosis_250507_49.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "lege maag", file: "signs/hh/gebaar/lege_maag_250507_25.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "loop", file: "signs/hh/gebaar/loop_250507_62.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "lopen", file: "signs/hh/gebaar/lopen_250507_54.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "maaltijd", file: "signs/hh/gebaar/maaltijd_250507_26.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "mag", file: "signs/hh/gebaar/mag_250507_2.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "mag (alt)", file: "signs/hh/gebaar/mag_250507_3.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "medicijn", file: "signs/hh/gebaar/medicijn_250507_7.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "met", file: "signs/hh/gebaar/met_250507_63.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "motor rijden", file: "signs/hh/gebaar/motor_rijden_250507_52.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "naar", file: "signs/hh/gebaar/naar_250507_64.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "neem in", file: "signs/hh/gebaar/neem_in_250507_23.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "niet", file: "signs/hh/gebaar/niet_250507_4.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "ouder", file: "signs/hh/gebaar/ouder_250507_39.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "ouder2", file: "signs/hh/gebaar/ouder2_250507_41.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "overleg", file: "signs/hh/gebaar/overleg_250507_31.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "park", file: "signs/hh/gebaar/park_250507_59.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "per dag", file: "signs/hh/gebaar/per_dag_250507_11.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "raadpleeg", file: "signs/hh/gebaar/raadpleeg_250507_33.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "school", file: "signs/hh/gebaar/school_250507_57.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "slik", file: "signs/hh/gebaar/slik_250507_9.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "speeltuin", file: "signs/hh/gebaar/speeltuin_250507_60.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "step", file: "signs/hh/gebaar/step_250507_56.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "temperatuur", file: "signs/hh/gebaar/temperatuur_250507_21.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "test", file: "signs/hh/gebaar/test_250507_1.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "uur", file: "signs/hh/gebaar/uur_250507_50.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "veiligheid", file: "signs/hh/gebaar/veiligheid_250507_8.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "verboden", file: "signs/hh/gebaar/verboden_250507_5.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "vermijd", file: "signs/hh/gebaar/vermijd_250507_44.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "voedsel", file: "signs/hh/gebaar/voedsel_250507_24.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "volwassenen", file: "signs/hh/gebaar/volwassenen_250507_38.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "werking", file: "signs/hh/gebaar/werking_250507_47.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "winkel", file: "signs/hh/gebaar/winkel_250507_58.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "zon licht", file: "signs/hh/gebaar/zon_licht_250507_20.glb", start: 0, end: null, folder: "hh-gebaar"},
  {name: "zwangerschap", file: "signs/hh/gebaar/zwangerschap_250507_28.glb", start: 0, end: null, folder: "hh-gebaar"},

  // ZNN folder
  {name: "Eerst naar de wc dan gaan we handen wassen en daarna gaan we eten", file: "signs/znn/Eerst_naar_de_wc_dan_gaan_we_handen_wassen_en_daarna_gaan_we_eten_250604_1_GlassesGuy.glb", start: 0, end: null, folder: "znn"},
  {name: "FODOK Welkomstwoord", file: "signs/znn/FODOK_Welkomstwoord_250604_2_GlassesGuy.glb", start: 0, end: null, folder: "znn"},
  {name: "Fijn om je weer te zien", file: "signs/znn/Fijn_om_je_weer_te_zien_250604_2_GlassesGuy.glb", start: 0, end: null, folder: "znn"},
  {name: "Heb je al geplast", file: "signs/znn/Heb_je_al_geplast_250604_3_GlassesGuy.glb", start: 0, end: null, folder: "znn"},
  {name: "Heb je genoeg gegeten", file: "signs/znn/Heb_je_genoeg_gegeten_250604_1_GlassesGuy.glb", start: 0, end: null, folder: "znn"},
  {name: "Is het warm", file: "signs/znn/Is_het_warm_250604_1_GlassesGuy.glb", start: 0, end: null, folder: "znn"},
  {name: "Nee jouw broer gaat nu ook naar bed dus jij gaat ook naar bed", file: "signs/znn/Nee_jouw_broer_gaat_nu_ook_naar_bed_dus_jij_gaat_ook_naar_bed_250604_2_GlassesGuy.glb", start: 0, end: null, folder: "znn"},
  {name: "Probeer je het zelf", file: "signs/znn/Probeer_je_het_zelf_250604_4_GlassesGuy.glb", start: 0, end: null, folder: "znn"},
  {name: "Wat vond je het stomste vandaag", file: "signs/znn/Wat_vond_je_het_stomste_vandaag_250604_17_GlassesGuy.glb", start: 0, end: null, folder: "znn"},
  {name: "eerst de vulva dan de billen vegen", file: "signs/znn/eerst_de_vulva_dan_de_billen_vegen_250604_1_GlassesGuy.glb", start: 0, end: null, folder: "znn"},

  // HH Zin folder
  {name: "12 jaar onder pil slikken niet", file: "signs/hh/zin/12_jaar_onder_pil_slikken_niet.glb", start: 0, end: null, folder: "hh-zin"},
  {name: "12 jaar ouder arts overleggen", file: "signs/hh/zin/12_jaar_ouder_arts_overleggen.glb", start: 0, end: null, folder: "hh-zin"},
  {name: "18 jaar ouder pil slikken", file: "signs/hh/zin/18_jaar_ouder_pil_slikken.glb", start: 0, end: null, folder: "hh-zin"},
  {name: "alcohol pil slikken niet", file: "signs/hh/zin/alcohol_pil_slikken_niet.glb", start: 0, end: null, folder: "hh-zin"},
  {name: "eten dan pil", file: "signs/hh/zin/eten_dan_pil.glb", start: 0, end: null, folder: "hh-zin"},
  {name: "ik bus naar park", file: "signs/hh/zin/ik_bus_naar_park.glb", start: 0, end: null, folder: "hh-zin"},
  {name: "ik fiets naar school", file: "signs/hh/zin/ik_fiets_naar_school.glb", start: 0, end: null, folder: "hh-zin"},
  {name: "ik loop naar winkel", file: "signs/hh/zin/ik_loop_naar_winkel.glb", start: 0, end: null, folder: "hh-zin"},
  {name: "ik rij naar school", file: "signs/hh/zin/ik_rij_naar_school.glb", start: 0, end: null, folder: "hh-zin"},
  {name: "ik step naar speeltuin", file: "signs/hh/zin/ik_step_naar_speeltuin.glb", start: 0, end: null, folder: "hh-zin"},
  {name: "pil bewaren droog", file: "signs/hh/zin/pil_bewaren_droog.glb", start: 0, end: null, folder: "hh-zin"},
  {name: "pil bewaren koud", file: "signs/hh/zin/pil_bewaren_koud.glb", start: 0, end: null, folder: "hh-zin"},
  {name: "pil bewaren zon niet", file: "signs/hh/zin/pil_bewaren_zon_niet.glb", start: 0, end: null, folder: "hh-zin"},
  {name: "pil fiets magniet", file: "signs/hh/zin/pil_fiets_magniet.glb", start: 0, end: null, folder: "hh-zin"},
  {name: "pil met eten", file: "signs/hh/zin/pil_met_eten.glb", start: 0, end: null, folder: "hh-zin"},
  {name: "pil met maagleeg", file: "signs/hh/zin/pil_met_maagleeg.glb", start: 0, end: null, folder: "hh-zin"},
  {name: "pil motorrijden magniet", file: "signs/hh/zin/pil_motorrijden_magniet.glb", start: 0, end: null, folder: "hh-zin"},
  {name: "pil perdag drie", file: "signs/hh/zin/pil_perdag_drie.glb", start: 0, end: null, folder: "hh-zin"},
  {name: "pil perdag twee", file: "signs/hh/zin/pil_perdag_twee.glb", start: 0, end: null, folder: "hh-zin"},
  {name: "pil perdag vijf", file: "signs/hh/zin/pil_perdag_vijf.glb", start: 0, end: null, folder: "hh-zin"},
  {name: "pil rijden magwel", file: "signs/hh/zin/pil_rijden_magwel.glb", start: 0, end: null, folder: "hh-zin"},
  {name: "pil slikken alcohol 24 uur wachten", file: "signs/hh/zin/pil_slikken_alcohol_24_uur_wachten.glb", start: 0, end: null, folder: "hh-zin"},
  {name: "pil slikken alcohol beinvloeden", file: "signs/hh/zin/pil_slikken_alcohol_beinvloeden.glb", start: 0, end: null, folder: "hh-zin"},
  {name: "zwanger arts overleg pil slikken", file: "signs/hh/zin/zwanger_arts_overleg_pil_slikken.glb", start: 0, end: null, folder: "hh-zin"},
  {name: "zwanger arts overleggen pil slikken", file: "signs/hh/zin/zwanger_arts_overleggen_pil_slikken.glb", start: 0, end: null, folder: "hh-zin"},
  {name: "zwanger pil magniet", file: "signs/hh/zin/zwanger_pil_magniet.glb", start: 0, end: null, folder: "hh-zin"}
];


// Mapping to get the item from the name
export const availableSignsMap = availableSigns.reduce((acc, sign) => {
  acc[sign.name] = sign;
  return acc;
}
, {});  